apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-immediate
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"  # Don't override default if not intended
provisioner: rancher.io/local-path-immediate
volumeBindingMode: Immediate
reclaimPolicy: Delete
---
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-immediate-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-immediate-sa
  namespace: local-path-immediate-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-immediate-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-immediate-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-immediate-role
subjects:
  - kind: ServiceAccount
    name: local-path-immediate-sa
    namespace: local-path-immediate-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-immediate
  namespace: local-path-immediate-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-immediate
  template:
    metadata:
      labels:
        app: local-path-immediate
    spec:
      serviceAccountName: local-path-immediate-sa
      containers:
        - name: local-path-immediate-container
          image: rancher/local-path-provisioner:v0.0.24
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - --config
            - /etc/config/config.json
            - --provisioner-name
            - rancher.io/local-path-immediate
          volumeMounts:
            - mountPath: /etc/config/
              name: config-volume
            - mountPath: /opt/local-path-immediate
              name: local-path
      volumes:
        - name: config-volume
          configMap:
            name: local-path-immediate-config
        - name: local-path
          hostPath:
            path: /opt/local-path-immediate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-immediate-config
  namespace: local-path-immediate-ns
data:
  config.json: |
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/opt/local-path-immediate"]
        }
      ]
    }
