apiVersion: v1
kind: Namespace
metadata:
  name: local-path-immediate-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-immediate-config
  namespace: local-path-immediate-ns
data:
  config.json: |-
    {
      "nodePathMap": [
        {
          "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths": ["/opt/local-path-immediate"]
        }
      ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
        - name: helper-pod
          image: busybox
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-immediate-sa
  namespace: local-path-immediate-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-immediate-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "persistentvolumes", "configmaps", "pods", "pods/log", "events"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-immediate-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-immediate-role
subjects:
  - kind: ServiceAccount
    name: local-path-immediate-sa
    namespace: local-path-immediate-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-immediate
  namespace: local-path-immediate-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-immediate
  template:
    metadata:
      labels:
        app: local-path-immediate
    spec:
      serviceAccountName: local-path-immediate-sa
      containers:
        - name: local-path-immediate
          image: rancher/local-path-provisioner:v0.0.32
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
            - --provisioner-name
            - rancher.io/local-path-immediate
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_MOUNT_PATH
              value: /etc/config/
          volumeMounts:
            - mountPath: /etc/config/
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: local-path-immediate-config

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-immediate
provisioner: rancher.io/local-path-immediate
volumeBindingMode: Immediate
reclaimPolicy: Delete
