apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win-upload-test
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win-upload-test
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: cdrom
              cdrom:
                bus: sata
            - name: virtio
              cdrom:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: cdrom
          persistentVolumeClaim:
            claimName: windows-iso
        - name: virtio
          persistentVolumeClaim:
            claimName: virtio-iso


https://docs.google.com/document/d/1gSrblmCNHZDJiG-rBrToL3hXl85KU6iTFbogOvWRzK4/edit?usp=sharing
