apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-vdi
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows-vdi
    spec:
      domain:
        firmware:
          bootloader:
            efi: {}  # Use UEFI boot
        features:
          smm:
            enabled: true  # Required for Secure Boot
        cpu:
          cores: 2
        resources:
          requests:
            memory: 6Gi  # More than minimum 4GiB
        devices:
          tpm:
            type: tpm2  # TPM 2.0 required by Windows 11
          disks:
            - name: cdrom-disk
              cdrom:
                bus: sata
              bootOrder: 1
            - name: harddisk
              disk:
                bus: virtio
              bootOrder: 2
            - name: virtio-disk
              cdrom:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: cdrom-disk
          persistentVolumeClaim:
            claimName: windows-iso
        - name: harddisk
          persistentVolumeClaim:
            claimName: win-vdi-disk
        - name: virtio-disk
          persistentVolumeClaim:
            claimName: virtio-iso
